# def fun(x):
#     print(x) #here def you dont give --> syntax error

# a = 10/0
# print(a) # zero divisible by anything is infine --> ZeroDivisionError --> logical error
# # it occcurs during excecution

# '''
# syntax error 
# --> syntax mistake  
# -->spelling mistake, don't give colunn, did not indent, not give def keyword, 
# not give class befor class create....
# --> easily identify the interpreter
# --> occures before runtime --> error occures before excecution 

# exception errors 
# --> logical mistake.
# --> it not identified by interpreter
# --> occures during runtime --> during excecution of time
# '''

# '''NORMAL TERMINATION'''
# '''where from the first line to last line every line succefully excecutes program ends'''
# print('server ready')
# p = int(input('enter amount\n'))
# t = int(input('time\n'))
# r = 10
# si = (p*t*r)/100
# print('interest',si)
# print('server stop') #critical statement 

# # when amount enter by 'ten lack' --> it is exception object --> it occures during runtime 

# '''Abrupt termination'''
# '''sudden stopping program, before completes its normal excecution'''

# '''Exception handling'''
# '''here abnorminal termination not occures, not crash my programm'''
# print('server ready')
# try:
#     p = int(input('enter amount\n'))
#     t = int(input('time\n'))
#     r = 10
#     si = (p*t*r)/100
#     print('interest',si)
# except:
#     print('please provide numeric value')
# print('server stop') #critical statement 
# '''except block only when activate when exception happens generated by in try block'''

'''optional else block'''
print('server ready')
try:
    p = int(input('enter amount\n'))
    t = int(input('time\n'))
    r = 10
except:
    print('please provide numeric value')
else: # here where no exception happens then else part excecute
    si = (p*t*r)/100
    print('interest',si)
print('server stop') #critical statement 